In [2]:
#from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

print("DONE")

2024-05-07 11:55:10.958566: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-07 11:55:10.958683: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-07 11:55:11.084248: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


DONE


In [3]:
def padding(seq):
  #max_len=max([len(x) for x in seq])
  #print(max_len)
  seq=pad_sequences(seq,padding='pre',maxlen=86)
  return seq

In [4]:
# dataExtraction

text=open("/kaggle/input/next-word-predictor-data/dataset.txt").read().split('.')
#print(text)

In [5]:
# dataPreprocessing

tk=Tokenizer()
tk.fit_on_texts(text)
seq=tk.texts_to_sequences(text)
# print(seq)

In [6]:
#print(tk.word_index)

In [7]:
#logicBuilding

x=[]
y=[]

for i in seq:
  for j in range(0,len(i)-1):
    # print(f"{i[:j+1]} and {i[j+1]}")
    x.append(i[:j+1])
    y.append(i[j+1])

x=padding(x)
y=np.array(y)
x=np.array(x)
#in order to perform task either we should go towards regression or classification
#now if we use regression then on fractional values it gives "no result" , so better we should go towards multiclass classification
#One Hot Encoding (OHE):
no_unique_word=len(tk.word_index)
y=to_categorical(y,num_classes=no_unique_word+1)
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x)
print(y)

[[   0    0    0 ...    0    0    6]
 [   0    0    0 ...    0    6  223]
 [   0    0    0 ...    6  223   20]
 ...
 [   0    0    0 ...  426   50 1225]
 [   0    0    0 ...   50 1225    8]
 [   0    0    0 ... 1225    8    4]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
print(no_unique_word)

5243


In [9]:
#modelBuilding
model=Sequential()
model.add(Embedding(input_dim=no_unique_word+1,output_dim=100, input_length=len(x[0])))
model.add(LSTM(150))
model.add(Dense(no_unique_word+1,activation='softmax'))
model.summary()

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(x,y,epochs=100)

Epoch 1/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 13s 10ms/step - accuracy: 0.0547 - loss: 6.9481
Epoch 2/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.0789 - loss: 6.1378
Epoch 3/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1126 - loss: 5.6883
Epoch 4/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1297 - loss: 5.3371
Epoch 5/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1426 - loss: 4.9904
Epoch 6/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1597 - loss: 4.6641
Epoch 7/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.1866 - loss: 4.3148
Epoch 8/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.2165 - loss: 3.9943
Epoch 9/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.2663 - loss: 3.6655
Epoch 10/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3070 - loss: 3.3802
Epoch 11/100
994/994 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.3566 - loss: 3.1025
Epoch 12/100
994/99

In [11]:
loss, accuracy = model.evaluate(x, y)
print(f'Train Loss: {loss}, Train Accuracy: {accuracy}')

994/994 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.9384 - loss: 0.1967
Train Loss: 0.20199915766716003, Train Accuracy: 0.9367566704750061


In [13]:
text="he"
print(text)
for i in range(20):
    
  seq=tk.texts_to_sequences([text])[0]
  x=pad_sequences([seq],padding='pre',maxlen=86)
  pos=np.argmax(model.predict(x))  # argmax(): finds out index which have highest value inside array
  #print(pos)

  for word,index in tk.word_index.items():
     if(index==pos):
         text=text+" "+word
         print(text)

he
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
he was still sitting
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still sitting with
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
he was still sitting with his
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
he was still sitting with his elbow
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
he was still sitting with his elbow upon
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still sitting with his elbow upon his
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still sitting with his elbow upon his knee
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still sitting with his elbow upon his knee considering
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still sitting with his elbow upon his knee considering how
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
he was still sitting with his elbow upon his knee considering how he
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
he was still sitting with his elbow u